spring:
  application:
    name: demo

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  web:
    error:
      include-message: always

logging:
  level:
    org.springframework.web: DEBUG